export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_UPDATE_PROFILE = "AUTH_UPDATE_PROFILE";
export const AUTH_SET_PROFILE = "AUTH_SET_PROFILE";

export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
