# Generated by Django 4.0.1 on 2022-01-21 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_storelabel_name'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(default='Item is not available', on_delete=django.db.models.deletion.SET_DEFAULT, to='store.product'),
        ),
    ]
