# Generated by Django 4.0.1 on 2022-01-13 23:29

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_slug_alter_store_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storelabel',
            name='name',
            field=models.CharField(max_length=255, validators=[store.models.StoreLabel.validate_tag_name_case]),
        ),
    ]
